### ISSUE TITLE
Not an issue, just a question.  Any reason to re-encode?

### ISSUE THREAD

**Issue by deanhuff** [lisamelton/other_video_transcoding#200]
I've been using your old scripts for years and years.  I'm just now getting around to updating my workflow from the legacy transcode-video.sh which used the batch.sh and queue file. 

My push to switch over to the new stuff is that I finally got a M2 Mac w/ some hardware accelerated horsepower.

I have the storage space available on my NAS, so I've just kept the master dumps from all of my blue rays.  

My question is:
Would there be any reason to re-encode my movies from source using your current transcoder tools?  Could I experience any better video quality or compression vs the output from the legacy scripts I've used in the past?

Feel free to close this post at any time.

**Comment by ttyS0** [comment]
Not speaking for Lisa, but I think this falls directly into the "it depends" bucket. 

In my opinion, run one or two of your favorite titles through the new process, and see if you like the outcome better than the existing. And "better" here might just be that it looks just as good, but takes up less space. Based on that, then expand it out to the rest of your library. 

Everyone is going to have a different approach, and they're all correct, which is what makes this a difficult thing to tease out. Some folks will look at encodes as an academic interest, and only use the full size originals in regular usage. Others will try and adjust for the best subjective quality, and not care about storage. Others will optimize for acceptable quality at the smallest possible size. And then there's dozens (hundreds?) of variation in-between and all around. :) 

So, to address your actual question. Is there any reason to re-encode? Sure! But the headache is that reason is best tailored to what it is you're needing. 

Even something like "...I got a new M2 Mac, and want to see if the hardware acceleration quality is acceptable for me." If you find it is, maybe you'll use that for the rest of your collection. 

Since you keep your sources (_always_ a good idea, by the way), the "fiddle factor" is high (as it should be). :)

**Comment by lisamelton** [comment]
@deanhuff Thank you for being such a long-time user of my tools!

I think @ttyS0 's take on this is spot on. (Thanks, Sean!) There's no reason to re-encode unless you don't like the quality or output size of your current transcodings. That's basically it. But I re-encode quite often because, as Sean diagnosed, I really like to fiddle with things. YMMV.

**Comment by deanhuff** [comment]
@ttyS0, @lisamelton Thanks for the thoughtful replies.  I may play around with re-ripping a few of my favorite films and do a comparison test.
